<?xml version="1.0" encoding="utf-8"?><Database Name="SistemaDeCompras" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=BRUNO\SQLEXPRESS;Initial Catalog=SistemaDeCompras;Integrated Security=True;Application Name=EntityFramework" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SistemaDeComprasConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tb_Embalagem" Member="tb_Embalagems">
    <Type Name="tb_Embalagem">
      <Column Name="id_embalagem" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="embalagem" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Association Name="tb_Embalagem_tb_Produto" Member="tb_Produtos" ThisKey="id_embalagem" OtherKey="embalagem" Type="tb_Produto" />
    </Type>
  </Table>
  <Table Name="dbo.tb_Usuario" Member="tb_Usuarios">
    <Type Name="tb_Usuario">
      <Column Name="id_usuario" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nome" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="senha" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="token" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="tb_Usuario_tb_ListaDeIten" Member="tb_ListaDeItens" ThisKey="id_usuario" OtherKey="id_usuario" Type="tb_ListaDeIten" />
      <Association Name="tb_Usuario_tb_ListaDeProduto" Member="tb_ListaDeProdutos" ThisKey="id_usuario" OtherKey="id_usuario" Type="tb_ListaDeProduto" />
    </Type>
  </Table>
  <Table Name="dbo.tb_Item" Member="tb_Items">
    <Type Name="tb_Item">
      <Column Name="id_item" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_estabelecimento" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_produto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="preco" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="qualificacao" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="data" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="tb_Produto_tb_Item" Member="tb_Produto" ThisKey="id_produto" OtherKey="id_produto" Type="tb_Produto" IsForeignKey="true" />
      <Association Name="tb_Estabelecimento1_tb_Item" Member="tb_Estabelecimento" Storage="_tb_Estabelecimento1" ThisKey="id_estabelecimento" OtherKey="id_estabelecimento" Type="tb_Estabelecimento" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_ItemDaLista" Member="tb_ItemDaListas">
    <Type Name="tb_ItemDaLista">
      <Column Name="id_lista" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nome_produto" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="marca_produto" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="preco" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="unidade" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="quantidade" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="tb_ListaDeIten_tb_ItemDaLista" Member="tb_ListaDeIten" ThisKey="id_lista" OtherKey="id_listaDeItens" Type="tb_ListaDeIten" IsForeignKey="true" />
      <Association Name="tb_Unidade_tb_ItemDaLista" Member="tb_Unidade" ThisKey="unidade" OtherKey="id_unidade" Type="tb_Unidade" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_ListaDeItens" Member="tb_ListaDeItens">
    <Type Name="tb_ListaDeIten">
      <Column Name="id_listaDeItens" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="dataDeCompras" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="id_usuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="tb_ListaDeIten_tb_ItemDaLista" Member="tb_ItemDaListas" ThisKey="id_listaDeItens" OtherKey="id_lista" Type="tb_ItemDaLista" />
      <Association Name="tb_Usuario_tb_ListaDeIten" Member="tb_Usuario" ThisKey="id_usuario" OtherKey="id_usuario" Type="tb_Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_ListaDeProdutos" Member="tb_ListaDeProdutos">
    <Type Name="tb_ListaDeProduto">
      <Column Name="id_listaDeProdutos" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nome" Type="System.String" DbType="VarChar(33)" CanBeNull="true" />
      <Column Name="id_usuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="tb_ListaDeProduto_tb_ProdutoDaLista" Member="tb_ProdutoDaListas" ThisKey="id_listaDeProdutos" OtherKey="id_lista" Type="tb_ProdutoDaLista" />
      <Association Name="tb_Usuario_tb_ListaDeProduto" Member="tb_Usuario" ThisKey="id_usuario" OtherKey="id_usuario" Type="tb_Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_Marca" Member="tb_Marcas">
    <Type Name="tb_Marca">
      <Column Name="id_marca" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="marca" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Association Name="tb_Marca_tb_Produto" Member="tb_Produtos" ThisKey="id_marca" OtherKey="marca" Type="tb_Produto" />
    </Type>
  </Table>
  <Table Name="dbo.tb_Ocorrencia" Member="tb_Ocorrencias">
    <Type Name="tb_Ocorrencia">
      <Column Name="id_ocorrencia" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ocorrencia" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Association Name="tb_Ocorrencia_tb_ProdutoInvalido" Member="tb_ProdutoInvalidos" ThisKey="id_ocorrencia" OtherKey="ocorrencia" Type="tb_ProdutoInvalido" />
    </Type>
  </Table>
  <Table Name="dbo.tb_Produto" Member="tb_Produtos">
    <Type Name="tb_Produto">
      <Column Name="id_produto" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nome" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="marca" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="codigoDeBarras" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="tipoCodigoDeBarras" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="unidade" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="embalagem" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="tb_Produto_tb_Item" Member="tb_Items" ThisKey="id_produto" OtherKey="id_produto" Type="tb_Item" />
      <Association Name="tb_Produto_tb_ProdutoDaLista" Member="tb_ProdutoDaListas" ThisKey="id_produto" OtherKey="id_produto" Type="tb_ProdutoDaLista" />
      <Association Name="tb_Produto_tb_ProdutoInvalido" Member="tb_ProdutoInvalidos" ThisKey="id_produto" OtherKey="id_produtoAntigo" Type="tb_ProdutoInvalido" />
      <Association Name="tb_Produto_tb_ProdutoInvalido1" Member="tb_ProdutoInvalidos1" ThisKey="id_produto" OtherKey="id_produtoNovo" Type="tb_ProdutoInvalido" />
      <Association Name="tb_Embalagem_tb_Produto" Member="tb_Embalagem" ThisKey="embalagem" OtherKey="id_embalagem" Type="tb_Embalagem" IsForeignKey="true" />
      <Association Name="tb_Marca_tb_Produto" Member="tb_Marca" ThisKey="marca" OtherKey="id_marca" Type="tb_Marca" IsForeignKey="true" />
      <Association Name="tb_Unidade_tb_Produto" Member="tb_Unidade" ThisKey="unidade" OtherKey="id_unidade" Type="tb_Unidade" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_ProdutoDaLista" Member="tb_ProdutoDaListas">
    <Type Name="tb_ProdutoDaLista">
      <Column Name="id_produto" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_lista" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="quantidade" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="tb_ListaDeProduto_tb_ProdutoDaLista" Member="tb_ListaDeProduto" ThisKey="id_lista" OtherKey="id_listaDeProdutos" Type="tb_ListaDeProduto" IsForeignKey="true" />
      <Association Name="tb_Produto_tb_ProdutoDaLista" Member="tb_Produto" ThisKey="id_produto" OtherKey="id_produto" Type="tb_Produto" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_ProdutoInvalido" Member="tb_ProdutoInvalidos">
    <Type Name="tb_ProdutoInvalido">
      <Column Name="id_produtoAntigo" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_produtoNovo" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ocorrencia" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="quantidadeDeOcorrencias" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="tb_Produto_tb_ProdutoInvalido" Member="tb_Produto" ThisKey="id_produtoAntigo" OtherKey="id_produto" Type="tb_Produto" IsForeignKey="true" />
      <Association Name="tb_Produto_tb_ProdutoInvalido1" Member="tb_Produto1" ThisKey="id_produtoNovo" OtherKey="id_produto" Type="tb_Produto" IsForeignKey="true" />
      <Association Name="tb_Ocorrencia_tb_ProdutoInvalido" Member="tb_Ocorrencia" ThisKey="ocorrencia" OtherKey="id_ocorrencia" Type="tb_Ocorrencia" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_Tipo" Member="tb_Tipos">
    <Type Name="tb_Tipo">
      <Column Name="id_tipo" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tipo" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_Unidade" Member="tb_Unidades">
    <Type Name="tb_Unidade">
      <Column Name="id_unidade" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="unidade" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Association Name="tb_Unidade_tb_ItemDaLista" Member="tb_ItemDaListas" ThisKey="id_unidade" OtherKey="unidade" Type="tb_ItemDaLista" />
      <Association Name="tb_Unidade_tb_Produto" Member="tb_Produtos" ThisKey="id_unidade" OtherKey="unidade" Type="tb_Produto" />
    </Type>
  </Table>
  <Table Name="dbo.tb_Estabelecimento" Member="tb_Estabelecimentos">
    <Type Name="tb_Estabelecimento">
      <Column Name="id_estabelecimento" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nome" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="bairro" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="cidade" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="numero" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="latitude" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="longitude" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="tb_Estabelecimento1_tb_Item" Member="tb_Items" ThisKey="id_estabelecimento" OtherKey="id_estabelecimento" Type="tb_Item" />
    </Type>
  </Table>
</Database>