//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComprasDigital.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SistemaDeComprasEntities1 : DbContext
    {
        public SistemaDeComprasEntities1()
            : base("name=SistemaDeComprasEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tb_Estabelecimento> tb_Estabelecimento { get; set; }
        public DbSet<tb_Item> tb_Item { get; set; }
        public DbSet<tb_ItemDaLista> tb_ItemDaLista { get; set; }
        public DbSet<tb_ListaDeItens> tb_ListaDeItens { get; set; }
        public DbSet<tb_ListaDeProdutos> tb_ListaDeProdutos { get; set; }
        public DbSet<tb_Marca> tb_Marca { get; set; }
        public DbSet<tb_Ocorrencia> tb_Ocorrencia { get; set; }
        public DbSet<tb_Produto> tb_Produto { get; set; }
        public DbSet<tb_ProdutoDaLista> tb_ProdutoDaLista { get; set; }
        public DbSet<tb_ProdutoInvalido> tb_ProdutoInvalido { get; set; }
        public DbSet<tb_Tipo> tb_Tipo { get; set; }
        public DbSet<tb_Unidade> tb_Unidade { get; set; }
        public DbSet<tb_Usuario> tb_Usuario { get; set; }
    }
}
