//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComprasDigital.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Estabelecimento
    {
        public tb_Estabelecimento()
        {
            this.tb_Item = new HashSet<tb_Item>();
        }
    
        public int id_estabelecimento { get; set; }
        public string nome { get; set; }
        public string bairro { get; set; }
        public string cidade { get; set; }
        public int numero { get; set; }
    
        public virtual ICollection<tb_Item> tb_Item { get; set; }
    }
}
