//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComprasDigital.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Ocorrencia
    {
        public tb_Ocorrencia()
        {
            this.tb_ProdutoInvalido = new HashSet<tb_ProdutoInvalido>();
        }
    
        public int id_ocorrencia { get; set; }
        public string ocorrencia { get; set; }
    
        public virtual ICollection<tb_ProdutoInvalido> tb_ProdutoInvalido { get; set; }
    }
}
