//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComprasDigital.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ProdutoDaLista
    {
        public string nome_produto { get; set; }
        public int marca_produto { get; set; }
        public int id_lista { get; set; }
        public int quantidade { get; set; }
    
        public virtual tb_ListaDeProdutos tb_ListaDeProdutos { get; set; }
        public virtual tb_Produto tb_Produto { get; set; }
    }
}
