//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComprasDigital.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ProdutoInvalido
    {
        public string nome_produtoAntigo { get; set; }
        public int marca_produtoAntigo { get; set; }
        public string nome_produtoNovo { get; set; }
        public int marca_produtoNovo { get; set; }
        public int ocorrencia { get; set; }
        public int quantidadeDeOcorrencias { get; set; }
    
        public virtual tb_Ocorrencia tb_Ocorrencia { get; set; }
        public virtual tb_Produto tb_Produto { get; set; }
        public virtual tb_Produto tb_Produto1 { get; set; }
    }
}
