//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComprasDigital.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Unidade
    {
        public tb_Unidade()
        {
            this.tb_Produto = new HashSet<tb_Produto>();
        }
    
        public int id_unidade { get; set; }
        public string unidade { get; set; }
    
        public virtual ICollection<tb_Produto> tb_Produto { get; set; }
    }
}
