//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComprasDigital.Classes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SistemaDeComprasEntities : DbContext
    {
        public SistemaDeComprasEntities()
            : base("name=SistemaDeComprasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tb_Estabelecimento> tb_Estabelecimento { get; set; }
        public virtual DbSet<tb_Item> tb_Item { get; set; }
        public virtual DbSet<tb_ListaDeItens> tb_ListaDeItens { get; set; }
        public virtual DbSet<tb_ListaDeProdutos> tb_ListaDeProdutos { get; set; }
        public virtual DbSet<tb_Produto> tb_Produto { get; set; }
        public virtual DbSet<tb_ProdutosInvalidos> tb_ProdutosInvalidos { get; set; }
        public virtual DbSet<tb_Usuario> tb_Usuario { get; set; }
        public virtual DbSet<tb_ItemDaLista> tb_ItemDaLista { get; set; }
        public virtual DbSet<tb_ProdutoDaLista> tb_ProdutoDaLista { get; set; }
    }
}
