//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComprasDigital.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ItemDaLista
    {
        public int id_item { get; set; }
        public int id_listaI { get; set; }
        public int quantidade { get; set; }
    
        public virtual tb_Item tb_Item { get; set; }
        public virtual tb_ListaDeItens tb_ListaDeItens { get; set; }
    }
}
