//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComprasDigital.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ListaDeItens
    {
        public tb_ListaDeItens()
        {
            this.tb_ItemDaLista = new HashSet<tb_ItemDaLista>();
        }
    
        public int id_listaDeItens { get; set; }
        public System.DateTime dataDeCompras { get; set; }
        public int id_usuario { get; set; }
    
        public virtual ICollection<tb_ItemDaLista> tb_ItemDaLista { get; set; }
        public virtual tb_Usuario tb_Usuario { get; set; }
    }
}
