//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComprasDigital.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ListaDeProdutos
    {
        public tb_ListaDeProdutos()
        {
            this.tb_ProdutoDaLista = new HashSet<tb_ProdutoDaLista>();
        }
    
        public int id_listaDeProdutos { get; set; }
        public string nome { get; set; }
        public int id_usuario { get; set; }
    
        public virtual tb_Usuario tb_Usuario { get; set; }
        public virtual ICollection<tb_ProdutoDaLista> tb_ProdutoDaLista { get; set; }
    }
}
